# Use Node.js 20 as the base image
FROM node:20

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and install dependencies
COPY package*.json ./
RUN npm install

# Copy the remaining application files
COPY . .

# Ensure bcrypt works by rebuilding native dependencies
RUN npm rebuild bcrypt

# Build the application
RUN npm run build

# Expose the backend port
EXPOSE 3000

# # Start the server
# CMD ["npm", "start"]
